.TH RTSAI 1 "Your Program Version"
.SH NAME
RTSAI \- Description of your program
.SH SYNOPSIS
RTSAI [options]
.SH DESCRIPTION
RTSAI is a program that ...
.SH OPTIONS
This section describes the available options for RTSAI.
.PP
.TP
\-h, \-\-help
Display the help message for RTSAI.
.SH AUTHOR
Your Name
.SH COPYRIGHT
Copyright (C) YYYY Your Name
.SH SEE ALSO
Any related programs or references